export enum screens {
  APP = 'APP',

  HOME = 'HOME',

  LEARN = 'LEARN',
  SELECT_TEST = 'SELECT_TEST',
  COLLATION_TEST = 'COLLATION_TEST',
  VISUALIZATION_TEST = 'VISUALIZATION_TEST',
  WRITING_TEST = 'WRITING_TEST',
}
